(() => {
  "use strict";

  const CONFIG = { language: "en-IN", rate: 0.94, pitch: 1.02 };
  const $ = id => document.getElementById(id);
  const panel = $("pujaPanel"), launcher = $("pujaLauncher"), close = $("pujaClose"), form = $("pujaForm"), input = $("pujaInput"), messages = $("pujaMessages"), mic = $("pujaMic"), avatar = $("pujaAvatar"), mini = $("pujaMiniAvatar"), status = $("pujaStatus"), stopBtn = $("pujaStopSpeaking");
  if (!panel || !launcher || !form || !input || !messages) return;

  const KB = [
    {id:"about",title:"Sage Harvest",route:"about.html",keys:["sage harvest","company","firm","advisory","website"],phrases:["what is sage harvest","tell me about sage harvest","what does sage harvest do","what is this website"],answer:"Sage Harvest Agro is an independent, practitioner-led advisory firm focused on seed and agri-business supply chains. In simple terms, it helps organizations understand how their operations work, identify constraints and design better systems for transformation, growth and resilience.",more:"The website brings this perspective together across supply-chain transformation, Digital & AI, sustainability and climate, due diligence, and international expansion."},
    {id:"services",title:"Services",route:"services.html",keys:["services","service","consulting","advisory","offer","help"],phrases:["what services do you provide","what services do you offer","what can sage harvest help with","how can you help a company"],answer:"Sage Harvest works across supply-chain transformation, Digital & AI, sustainability and climate, supply-chain due diligence and operational risk, and international expansion and cross-border trade.",more:"The common thread is practical execution: understand the operating problem first, then choose the right combination of process, data, technology and management action."},
    {id:"supply",title:"Supply Chain Transformation",route:"services.html",keys:["supply chain","seed","production","planning","processing","quality","warehouse","inventory","distribution","traceability","operations"],phrases:["how do you improve supply chains","tell me about supply chain transformation","what is seed supply chain","how does sage harvest approach supply chains"],answer:"Sage Harvest looks at the seed supply chain as one connected system rather than isolated functions. That means looking across production planning, processing, quality, warehousing, inventory, distribution and traceability.",more:"The objective is not simply to optimise one function. It is to understand how a decision in one part of the network affects cost, service, quality, risk and outcomes elsewhere."},
    {id:"ai",title:"Digital & AI",route:"digital-ai.html",keys:["digital","ai","artificial intelligence","machine learning","regression","forecast","forecasting","analytics","satellite","weather","data","traceability"],phrases:["tell me about digital and ai","how can ai help","how do you use ai","what is your ai work","tell me about machine learning","what about satellite data","what about forecasting"],answer:"Sage Harvest treats Digital & AI as a decision-support capability rather than technology for its own sake. The website covers AI and analytics, forecasting, satellite and weather intelligence, traceability and data-driven decision support for agricultural supply chains.",more:"The broader idea is to connect field and operational data with better planning and management decisions. That can include forecasting demand or supply, identifying patterns, and using satellite or weather information where it adds decision value."},
    {id:"sustainability",title:"Sustainability & Climate",route:"sustainability.html",keys:["sustainability","climate","carbon","mrv","emissions","resource efficiency","climate smart","resilience"],phrases:["tell me about sustainability","how do you address climate","tell me about carbon","what is mrv","how can supply chains become sustainable"],answer:"Sage Harvest connects sustainability with the way the supply chain actually operates. The website covers climate-smart supply chains, resource efficiency, carbon and MRV-oriented approaches, and sustainability assurance.",more:"The practical perspective is to connect sustainability goals with operational decisions, rather than treating climate and supply-chain performance as separate subjects."},
    {id:"ma",title:"M&A Due Diligence",route:"ma-due-diligence.html",keys:["m&a","m and a","merger","acquisition","due diligence","operational risk","investor","transaction"],phrases:["tell me about m&a","tell me about due diligence","how do you assess an acquisition","what is operational risk assessment","can you help investors"],answer:"Sage Harvest's due-diligence perspective is about understanding the operational reality behind the numbers. That can include production, infrastructure, inventory, quality, capacity and operating risks.",more:"The purpose is to help management teams, investors and transaction teams see operational strengths, constraints and risks that may not be obvious from financial information alone."},
    {id:"international",title:"International Expansion & Trade",route:"international-expansion.html",keys:["international","global","export","cross border","india africa","africa","trade","market entry","partner","expansion"],phrases:["tell me about international expansion","how can you help with exports","what about india africa","do you help companies enter new markets","tell me about global expansion"],answer:"Sage Harvest supports organizations exploring international markets, export opportunities, strategic partnerships and cross-border supply chains.",more:"The international focus connects market intelligence, commercial strategy, partner identification and facilitation with disciplined execution."},
    {id:"founder",title:"Founder",route:"founder.html",keys:["founder","raja","raja vadlamani","principal advisor","corteva","advanta","shriram bioseed","seedworks"],phrases:["who is raja vadlamani","tell me about raja","who founded sage harvest","who is the founder"],answer:"Raja Vadlamani is the Founder and Principal Advisor of Sage Harvest. The website describes nearly four decades across the seed and agri-business ecosystem, with experience across Corteva, Advanta, Shriram Bioseed and SeedWorks International.",more:"His Sage Harvest role brings that operating experience into independent advisory work across supply chains, transformation, technology, sustainability and international opportunity."},
    {id:"insights",title:"Insights",route:"insights.html",keys:["insights","articles","article","writing","publication","linkedin","read"],phrases:["where are your articles","show me your articles","tell me about your insights","what have you written","where can i read your articles"],answer:"The Insights section is Sage Harvest's space for practical perspectives on seed supply chains, AI, sustainability and industry transformation.",more:"You can use Insights in the main navigation to explore the published material."},
    {id:"youtube",title:"Supply Chain With Raja",route:"https://www.youtube.com/@rajavadlamani",keys:["youtube","video","videos","channel","watch"],phrases:["where is your youtube","tell me about supply chain with raja","where can i watch your videos","do you have videos"],answer:"Supply Chain With Raja is the video knowledge platform associated with Sage Harvest. It extends the website's ideas through practical conversations and explainers around seed supply chains, AI, sustainability and industry transformation.",more:"You can open the YouTube channel whenever you want to explore the video content."},
    {id:"labs",title:"Labs",route:"labs.html",keys:["labs","lab","experiment","experiments","tools","innovation","prototype"],phrases:["what are the labs","tell me about labs","what do you experiment with","what tools have you built"],answer:"Labs is the practical experimentation space of Sage Harvest. It is intended for tools, experiments and emerging ideas that can make supply-chain decisions more useful and practical.",more:"It is where concepts can be explored in a hands-on way rather than remaining only as written advisory ideas."},
    {id:"cases",title:"Case Perspectives",route:"case-studies.html",keys:["case","cases","case studies","case perspectives","projects","experience","greenfield"],phrases:["show me your case studies","tell me about your case perspectives","what experience do you have","what projects have you worked on","tell me about greenfield projects"],answer:"Case Perspectives brings practical experience into the website, including supply-chain transformation, planning, technology, sustainability and operational challenges.",more:"The intention is to show how the ideas translate into real operating situations and decisions."},
    {id:"contact",title:"Contact",route:"contact.html",keys:["contact","email","phone","engage","conversation","talk","work together"],phrases:["how do i contact you","how can i get in touch","can we work together","how can i engage you","talk to someone"],answer:"Certainly. The Talk to Us and Contact sections are the best place to start a conversation with Sage Harvest. If you tell me what you are looking for, I can also guide you to the most relevant area of the site.",more:"For example, I can help you decide whether your question is more relevant to supply-chain transformation, Digital & AI, sustainability, due diligence or international expansion."}
  ];

  const stopPhrases = ["stop","stop talking","stop speaking","stop voice","be quiet","quiet please","please stop","thats enough","that's enough"];
  const followPhrases = ["tell me more","more","go on","explain more","say more","continue","what do you mean","can you explain","give me an example","example","why","how so","what about it","and what about that"];
  const filler = new Set("a an the is are do does did can could would you your i me my we us to for of and or in on about tell please what how who where why with this that it from".split(" "));
  const norm = s => String(s || "").toLowerCase().replace(/[’']/g, "").replace(/[^a-z0-9&\s-]/g, " ").replace(/\s+/g, " ").trim();
  const tokenSet = s => new Set(norm(s).split(" ").filter(w => w && !filler.has(w)));
  const isStop = s => { const n = norm(s); return stopPhrases.some(p => n === p || n.startsWith(p + " ")); };
  const isFollow = s => { const n = norm(s); return followPhrases.some(p => n === p || n.startsWith(p + " ")) || (n.length < 22 && /^(more|why|how|example|explain|continue)\b/.test(n)); };

  let topic = null, recognition = null, listening = false, pujaVoice = null;
  const synth = "speechSynthesis" in window ? window.speechSynthesis : null;

  function setState(state, label) { avatar?.classList.remove("speaking", "listening"); mini?.classList.remove("speaking", "listening"); if (state) { avatar?.classList.add(state); mini?.classList.add(state); } if (status && label) status.textContent = label; }
  function stopTalking() { if (synth) { synth.cancel(); try { synth.resume(); } catch (_) {} } setState(null, "Sage Harvest Guide"); }
  function addMessage(text, sender = "bot") { const row = document.createElement("div"); row.className = `puja-message puja-message-${sender}`; if (sender === "bot") { const a = document.createElement("div"); a.className = "puja-message-avatar"; a.textContent = "P"; row.appendChild(a); } const body = document.createElement("div"); body.className = "puja-message-content"; body.textContent = text; row.appendChild(body); messages.appendChild(row); messages.scrollTop = messages.scrollHeight; }
  function addLink(t) { if (!t?.route) return; const wrap = document.createElement("div"); wrap.className = "puja-navigation-link"; const a = document.createElement("a"); a.className = "puja-inline-link"; a.href = t.route; a.textContent = t.id === "youtube" ? "Open Supply Chain With Raja →" : `Explore ${t.title} →`; if (/^https?:/.test(t.route)) { a.target = "_blank"; a.rel = "noopener"; } wrap.appendChild(a); messages.appendChild(wrap); messages.scrollTop = messages.scrollHeight; }

  function chooseVoice() {
    if (!synth) return;
    const voices = synth.getVoices(), indian = voices.filter(v => /^en-IN/i.test(v.lang));
    const preferred = [/heera/i, /neerja/i, /swara/i, /zira/i, /jenny/i, /aria/i, /samantha/i, /susan/i, /female/i, /google.*female/i];
    pujaVoice = null; for (const re of preferred) { pujaVoice = indian.find(v => re.test(v.name)); if (pujaVoice) break; }
    pujaVoice = pujaVoice || indian[0] || voices.find(v => /female|zira|jenny|aria|samantha/i.test(v.name) && /^en/i.test(v.lang)) || voices.find(v => /^en/i.test(v.lang)) || voices[0] || null;
  }
  chooseVoice(); synth?.addEventListener("voiceschanged", chooseVoice);

  function speak(text) { if (!synth) return; stopTalking(); const u = new SpeechSynthesisUtterance(text); u.lang = CONFIG.language; u.rate = CONFIG.rate; u.pitch = CONFIG.pitch; if (pujaVoice) u.voice = pujaVoice; u.onstart = () => setState("speaking", `Puja is speaking${pujaVoice ? " · " + pujaVoice.name : ""}`); u.onend = () => setState(null, "Sage Harvest Guide"); u.onerror = () => setState(null, "Sage Harvest Guide"); synth.speak(u); }
  function score(q, t) { const n = norm(q), ts = tokenSet(q); let s = 0; t.phrases.forEach(p => { const x = norm(p); if (n === x) s += 20; else if (n.includes(x)) s += 11; }); t.keys.forEach(k => { const x = norm(k); if (n.includes(x)) s += x.includes(" ") ? 5 : 2; }); let hits = 0; ts.forEach(w => { if (t.keys.some(k => norm(k).split(" ").includes(w))) hits++; }); if (hits >= 2) s += Math.min(8, hits * 2); return s; }
  function find(q) { let best = null, bestScore = 0; KB.forEach(t => { const s = score(q, t); if (s > bestScore) { bestScore = s; best = t; } }); return bestScore >= 3 ? best : null; }
  function answerFor(t, q) { const n = norm(q); if (isFollow(q) && topic?.id === t.id) return `Of course. ${t.more}`; if (/\bwhy\b|\bbenefit\b|\bimportant\b|\bvalue\b/.test(n)) return `The important point is this: ${t.more}`; if (/\bhow\b|\bapproach\b|\bprocess\b|\bwork\b/.test(n)) return `In practical terms, ${t.answer} ${t.more}`; if (/\bexample\b/.test(n)) return `${t.answer} A useful way to think about it is: first understand the operating problem, then identify the constraint, and only then decide what process, data or technology is needed.`; return t.answer; }
  function respond(q) { const n = norm(q); if (/^(hi|hello|hey|good morning|good afternoon|good evening)\b/.test(n)) return { text: "Hello. I’m Puja, the virtual agent for Sage Harvest. It’s nice to have you here. What would you like to explore?" }; if (/\b(thank you|thanks|thankyou)\b/.test(n)) return { text: "You’re very welcome. If there is anything else you would like to explore on Sage Harvest, I’m happy to help." }; if (isFollow(q) && topic) return { text: answerFor(topic, q), topic }; const t = find(q); if (t) return { text: answerFor(t, q), topic: t }; if (/\b(what can i ask|what can you help|menu|sections|pages)\b/.test(n)) return { text: "You can ask me about Sage Harvest, our services, supply-chain transformation, Digital & AI, sustainability, M&A due diligence, international expansion, Raja Vadlamani, Insights, Labs, Case Perspectives or Supply Chain With Raja." }; return { text: "I’m not completely sure what you mean, and I don’t want to guess. Tell me what area interests you—such as supply chains, Digital & AI, sustainability, due diligence, international expansion or the Founder—and I’ll explain it in plain language." }; }
  function process(text) { const q = String(text || "").trim(); if (!q) return; if (isStop(q)) { stopTalking(); return; } stopTalking(); addMessage(q, "user"); const r = respond(q); if (r.topic) topic = r.topic; addMessage(r.text, "bot"); if (r.topic && /\b(where|link|page|watch|read|find)\b/.test(norm(q))) addLink(r.topic); speak(r.text); }

  launcher.addEventListener("click", () => { const open = panel.classList.toggle("open"); panel.setAttribute("aria-hidden", String(!open)); launcher.setAttribute("aria-expanded", String(open)); if (open) setTimeout(() => input.focus(), 80); });
  close?.addEventListener("click", () => { panel.classList.remove("open"); panel.setAttribute("aria-hidden", "true"); launcher.setAttribute("aria-expanded", "false"); });
  stopBtn?.addEventListener("click", stopTalking);
  form.addEventListener("submit", e => { e.preventDefault(); const q = input.value; input.value = ""; process(q); });
  document.querySelectorAll("[data-puja-question]").forEach(b => b.addEventListener("click", () => process(b.dataset.pujaQuestion || "")));

  const SR = window.SpeechRecognition || window.webkitSpeechRecognition;
  if (SR && mic) { recognition = new SR(); recognition.lang = CONFIG.language; recognition.interimResults = false; recognition.continuous = false; recognition.maxAlternatives = 1; recognition.onstart = () => { listening = true; stopTalking(); setState("listening", "Puja is listening…"); mic.classList.add("active"); }; recognition.onresult = e => { const heard = e.results[0][0].transcript.trim(); if (isStop(heard)) { stopTalking(); return; } process(heard); }; recognition.onerror = e => { if (e.error !== "aborted") addMessage(e.error === "not-allowed" ? "Please allow microphone access so I can listen to you." : "I didn’t catch that. Please try again or type your question."); }; recognition.onend = () => { listening = false; mic.classList.remove("active"); if (!synth?.speaking) setState(null, "Sage Harvest Guide"); }; mic.addEventListener("click", () => { if (listening) { recognition.stop(); return; } stopTalking(); try { recognition.start(); } catch (_) {} }); } else if (mic) { mic.disabled = true; mic.title = "Speech recognition is not supported in this browser"; }

  document.addEventListener("keydown", e => { if (e.key === "Escape") { stopTalking(); panel.classList.remove("open"); panel.setAttribute("aria-hidden", "true"); } });
})();